package org.example.view;

import org.example.controller.MealController;
import org.example.controller.ProfileController;
import org.example.model.*;
import org.example.model.UserModel.FitnessGoals;
import org.example.model.UserModel.Profile;

import javax.swing.*;
import javax.swing.event.HyperlinkEvent;
import java.awt.*;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

import static org.example.view.ViewUtility.*;

/**
 * This is the class for the Meal tab view in the main application. This view displays the meals
 * generated by the SpoonacularClient API. It allows sorting based on the user's activity goal and
 * produces buttons that generate recipe details.
 * <p>
 * Representation Invariant:
 * - user is not null
 * - savedRecipes is not null
 * - profileController and mealController is not null
 * </p>
 * <p>
 * Abstract Functions:
 * Meal tab with meal generation display:
 * - r.user = the current user profile
 * - r.savedRecipes = list of recipes generated for the user from ingredients
 * and sorted based on the user's fitness goal
 * </p>
 */

public class MealView extends JPanel {
    static int DEBUG = 1;
    Profile user;
    List<Recipe> savedRecipes = new ArrayList<>();
    MealController mealController;

    /**
     * checkRep for checking if representation invariant is violated
     */
    private void checkRep() {
        if (user == null) {
            throw new IllegalStateException("users is null");
        }
        if (savedRecipes == null) {
            throw new IllegalStateException("savedRecipes is null");
        }
        if (mealController == null) {
            throw new IllegalStateException("mealController is null");
        }
    }
  
    /**
     * Creates the view in the application for the Meal tab. Displays title text, buttons for
     * recipes, and displays the recipes details on button press. Uses the profile controller and
     * meal controller to control how the meal view displays and functions
     * @param profileController fetches profile to calculate user goal
     * @param mealController fetches recipe list to display buttons and information
     */
    public MealView(ProfileController profileController, MealController mealController){
        this.user = profileController.fetchProfile();

        this.savedRecipes = mealController.getSavedRecipes();
        this.mealController = mealController;
      
        initializePanel(this);

        String titleText = "Meals";
        if (user.goal != null) {
            if (user.goal == FitnessGoals.NONE){
                titleText += " for You";
            }
            else {
                titleText += " for " + user.goal.title;
            }
        }
        JLabel titleLabel = new JLabel(titleText);

        styleTitleLabel(titleLabel);
        titleLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
        add(titleLabel);
        add(Box.createRigidArea(new Dimension(0, 20)));

        if (!savedRecipes.isEmpty()) {
            // Sort recipes based on fitness goal
            List<Recipe> sortedRecipes = new ArrayList<>(savedRecipes);
            sortedRecipes.sort((r1, r2) -> {
                double calories1 = getCalories(r1);
                double calories2 = getCalories(r2);
                if (user.goal != null) {
                    switch (user.goal) {
                        case WEIGHT_LOSS:
                            return Double.compare(calories1, calories2); // Lower calories first
                        case MUSCLE_GAIN:
                            return Double.compare(calories2, calories1); // Higher calories first
                        default:
                            return 0; // No sorting for maintenance
                    }
                }
                return 0;
            });

            JPanel buttonPanel = new JPanel(new GridLayout(0, 2, 50, 50));
            buttonPanel.setBackground(LIGHT_GREEN);

            for (Recipe recipe : sortedRecipes) {
                if(DEBUG == 1){
                    Logger logger = Logger.getLogger(MealView.class.getName());
                    logger.info(String.valueOf(recipe));
                }
                // Create a panel for each recipe that will contain both button and label
                JPanel recipePanel = new JPanel();
                recipePanel.setLayout(new BoxLayout(recipePanel, BoxLayout.Y_AXIS));
                recipePanel.setBackground(LIGHT_GREEN);

                // Create and add the image button
                String recipeURL = recipe.image();
                URLImageButton urlImageButton = new URLImageButton();
                JButton recipeButton = urlImageButton.createImageButton(recipeURL, 240,
                    135, URLImageButton.FitMode.STRETCH);
                recipeButton.addActionListener(e -> showRecipeDetails(recipe));
                recipeButton.setAlignmentX(Component.CENTER_ALIGNMENT);
                recipePanel.add(recipeButton);

                // Add some vertical spacing between button and label
                recipePanel.add(Box.createRigidArea(new Dimension(0, 5)));

                // Create and add the title label with calories
                String titleWithCalories = String.format("%s (%.0f cal)",
                        Recipe.cutTitle(recipe.title()),
                        getCalories(recipe));
                JLabel titleBox = new JLabel(titleWithCalories);
                titleBox.setAlignmentX(Component.CENTER_ALIGNMENT);
                titleBox.setForeground(TEXT_COLOR);
                recipePanel.add(titleBox);

                // Add the recipe panel to the button panel
                buttonPanel.add(recipePanel);
            }

            JPanel centeringPanel = new JPanel(new FlowLayout(FlowLayout.CENTER));
            centeringPanel.setBackground(LIGHT_GREEN);
            centeringPanel.add(buttonPanel);
            add(centeringPanel);
        } else {
            JLabel noMealsLabel = new JLabel("No meals generated yet. Go to Grocery List" +
                " to generate meals!");
            noMealsLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
            noMealsLabel.setForeground(TEXT_COLOR);
            add(noMealsLabel);
        }
    }

    /**
     * On the recipe button press, displays a frame showing recipe details and link to the recipe
     * @param recipe recipe to display information for
     */
    private void showRecipeDetails(Recipe recipe) {
        JDialog dialog = new JDialog();
        dialog.setSize(500, 600);
        dialog.setLocationRelativeTo(this);

        JPanel detailsPanel = new JPanel();
        detailsPanel.setLayout(new BoxLayout(detailsPanel, BoxLayout.Y_AXIS));
        detailsPanel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        detailsPanel.setBackground(LIGHT_GREEN);

        // Create recipe details using JEditorPane
        JEditorPane detailsArea = new JEditorPane();
        detailsArea.setContentType("text/html");
        detailsArea.setEditable(false);
        detailsArea.setBackground(LIGHT_GREEN);
        detailsArea.putClientProperty(JEditorPane.HONOR_DISPLAY_PROPERTIES, Boolean.TRUE);

        // Build HTML content
        StringBuilder details = new StringBuilder();
        details.append("<html><body style='font-family: Arial; font-size: 10px; " +
            "background-color: rgb(220, 237, 218);'>");
        details.append("<p>Recipe: ").append(recipe.title()).append("</p>");

        // Add calories if available
        if (recipe.nutrition() != null && recipe.nutrition().nutrients() != null) {
            double calories = recipe.nutrition().nutrients().stream()
                    .filter(n -> n.name().equals("Calories"))
                    .findFirst()
                    .map(n -> n.amount())
                    .orElse(0.0);
            details.append("<p>Calories: ").append(calories).append("</p>");
        }

        // Add clickable source URL
        details.append("<p><b>Source: </b><a href='").append(recipe.sourceUrl()).append("'>")
                .append("Link to Recipe").append("</a></p>");

        // List used ingredients
        details.append("<p>Used ingredients:</p><ul>");
        for (Ingredient ingredient : recipe.usedIngredients()) {
            details.append("<li>").append(ingredient.original())
                    .append(" (").append(ingredient.amount())
                    .append(" ").append(ingredient.unit()).append(")</li>");
        }
        details.append("</ul>");

        // List missing ingredients
        details.append("<p>Missing ingredients:</p><ul>");
        for (Ingredient ingredient : recipe.missedIngredients()) {
            details.append("<li>").append(ingredient.original())
                    .append(" (").append(ingredient.amount())
                    .append(" ").append(ingredient.unit()).append(")</li>");
        }
        details.append("</ul></body></html>");

        detailsArea.setText(details.toString());

        // Add hyperlink listener
        detailsArea.addHyperlinkListener(e -> {
            if (e.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
                try {
                    Desktop.getDesktop().browse(new URI(e.getURL().toString()));
                } catch (IOException | URISyntaxException ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(dialog,
                            "Error opening link: " + ex.getMessage(),
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        });

        JScrollPane scrollPane = new JScrollPane(detailsArea);
        scrollPane.setPreferredSize(new Dimension(500, 700));
        detailsPanel.add(scrollPane);

        JButton closeButton = new JButton("Close");
        styleButton(closeButton);
        closeButton.setAlignmentX(Component.CENTER_ALIGNMENT);
        closeButton.addActionListener(e -> dialog.dispose());

        JButton saveRecipeButton = new JButton("Save Recipe");
        styleButton(saveRecipeButton);
        saveRecipeButton.setAlignmentX(Component.CENTER_ALIGNMENT);
        saveRecipeButton.addActionListener(e -> {
                mealController.starRecipe(recipe);
                System.out.println(mealController.getFavouriteRecipes());
            });

        detailsPanel.add(Box.createRigidArea(new Dimension(0, 10)));
        detailsPanel.add(closeButton);
        detailsPanel.add(saveRecipeButton);

        dialog.add(detailsPanel);
        dialog.setVisible(true);
    }

    /**
     * // Helper method to get calories from a recipe
     * @param recipe recipe to get calories from
     * @return double representing the recipe calories.
     */
    private double getCalories(Recipe recipe) {
        if (recipe.nutrition() != null && recipe.nutrition().nutrients() != null) {
            return recipe.nutrition().nutrients().stream()
                    .filter(n -> n.name().equals("Calories"))
                    .findFirst()
                    .map(n -> n.amount())
                    .orElse(0.0);
        }
        return 0.0;
    }

}
